name: dbua
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - hdf5storage
  - tqdm
  - typing_extensions
  - ffmpeg
  - pip
  - pip:
    - "jax[cuda12]"
    - jaxopt
    - optax
    - numpy>=2.0
    - matplotlib>=3.9
    - scipy